### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by chltjdrhd777** [chltjdrhd777/my-record#193]
사용 이모지 리스트 : ⌚️ 📱 📲 💻 ⌨️ 🖥 🖨 🖱 🖲 🕹🚲 🛵 🏍 🛺 🚨 🚔 🚍

## 🕹 SCSS/SASS의 장점
1. nesting 기능을 제공하기 때문에, CSS의 클래스 중복 선언에 의해 발생하는 예기치못한 스타일링 오류 완화
2. & 키워드를 이용하여 자기참조가 가능하기때문에 불필요한 selector 선언을 피할 수 있음
3. & 키워드가 자기참조를 한다는 방법을 응용하여 조건부 클래스를 깔끔하게 만들 수 있다.
```css
// 예를들면 아래의 코드는
.fa {
    &-small { font-size: 12px }
    &-medium { font-size: 14px }
    &-large { font-size: 16px }
}

// 아래와 같이 컴파일된다
.fs-small {
  font-size: 12px;
}
.fs-medium {
  font-size: 14px;
}
.fs-large {
  font-size: 16px;
}
```

4. $변수명: 속성값; 형태로 변수선언을 하듯 스타일값을 선언하여 중복을 방지한다
5. mixin - include를 이용해 중복으로 사용되는 동일 스타일셋을 객체처럼 묶어 사용하여 유지보수를 극대화한다
6. extend를 이용해 특정 셀렉터가 보유하는 디자인 내용을 상속할 수 있다.

## 🕹 SCSS, SASS의 차이점
SCSS는 nesting에서 중괄호와 세미콜론을 통한 클래스 구분이 가능하지만 sass는 그렇지 않기 떄문에 scss가 더 개발 경험으로 선호된다

```css
// sass /////
.list
  width: 100px
  float: left
  li
    color: red
    background: url("./image.jpg")
    &:last-child
      margin-right: -10px

// scss /////
.list {
  width: 100px;
  float: left;
  li {
    color: red;
    background: url("./image.jpg");
    &:last-child {
      margin-right: -10px;
    }
  }
}
```

## 🕹 id, clss 셀렉터의 차이점
id는 해당 요소가 유일함을 나타내기 위해서 사용한다. 이런 특성 덕택에 id는 class보다 우선순위가 높으며 id attribute가 존재하는 요소는 자동적으로 전역에 의해 설정되어 할당된다.

```js
// 예를들어, 아래와 같은 요소가 html 문서에 정의되었다고 할 경우
<input type="text" id="globalProp" value="value"/>

//전역에는 해당 id에 해당하는 프로퍼티가 DOM에 추가된다
alert(globalProp.type) // "text"
```

class는 어떠한 요소를 특정하게 네이밍하여 필요한 스타일링을 하거나, 해당 스타일링을 다른 요소에도 중복적으로 적용하고 싶을 때 사용한다.

## 🕹 css box model
모든 html 요소는 특정한 박스 형태로 만들어져 뷰포트에 페인팅된다.
이때 사용되는 옵션은 
- content : 요소 태그의 자식의 순수 크기이다. ( 텍스, 이미지 등)
- padding : border 이전에 영역을 설정한다
- border : 요소의 테두리이다.
- margin : 요소의 border 이외의 영역이다.

## 🕹 px, em, rem, vh, vw의 차이
- px : 뷰포트에 나타내는 픽셀의 갯수를 의미한다. ( 스크린은 픽셀을 통해서 디스플레이를한다 )
- em : 부모의 폰트사이즈를 기준으로 설정되는 상대단위길이다
- rem : 루트 요소의 폰트사이즈를 기준으로 설정되는 상대길이이다.
- vw/vh : 뷰포트를 기준으로 설정되는 상대길이이다. ( 브라우저의 랜더링 영역이라고 이해하면 된다 )

## 🕹 grid와 flex 차이
- grid는 영역을 테이블 형태로 행과 열로 분리하여 해당 구역에 컨텐츠를 집어넣는 2차원 레이아웃 방식이다.
```css
// 아래와 같이 설정할 경우, row 즉 가로들의 형태를 설정한다. 일반적으로 repeat을 이용한다.
grid-template-rows : repeat( 갯수, 각각 비율fr)

//minmax를 이용해 최소크기 지정이 가능하다 역시 가능하다
grid-template-rows : repeat( 3, minmax( 100px, auto) ) //최소 100px, 최대 콘텐츠크기

//한 줄에 컨텐츠가 몇개가 들어갈지 모르는 경우, 갯수가 부족하면 자동으로 빈공간을 채워 메꾸도록 할 수 있다.
//아래의 경우, 최소 크기를 부모의 20%로 잡고 있으므로 갯수가 빈다면 그만큼 빈공간이 생기지만, 그것을 자동으로 크기를 조절함으로써 메꾼다.
grid-template-rows : repeat( auto-fit, minmax(20%, auto) );

//한 줄에 컨텐츠가 몇개인지는 모르지만, 확장시키면서 메꾸고 싶지않다면 auto 시리즈를 사용하면된다.
//auto 시리즈는 컨텐츠 갯수를 굳이 지정하지 않으면서 grid 구조를 자동완성한다.
//아래처럼 사용하면, 그리드에 들어오는 내용은 알아서 최소 100px, 최대 컨텐츠크기로 만들어져 그리드로 들어온다.
grid-auto-rows : minmax(100px, auto);

//auto 시리즈는 크기비율의 반복을 지정해줄 수 있다.
grid-auto-rows : 1fr 2fr // 이렇게 지정하면 1비율과 2비율이 번걸아가마며 지정된다.

//grid는 번호와 span옵션을 통해 해당 요소가 그리드의 어디까지 차지하게 만들고 싶은지 설정할 수 있다.
display:grid;
grid-template-columns: repeat(auto-fill, minmax(25%, auto)) // 최소 25% 크기이므로 세로줄이 
최소 4개임을 알 수 있다.
grid-template-rows: repeat(5, minmax(50px,auto)) //최소 50px크기인 5개의 가로줄임을 알 수 있다.

item:nth-child(2) { grid-column: auto / span 3; } // 2번째 자식은, 자동설정 시작점부터(auto) 3칸을 차지한다.
item:nth-child(5) { grid-column: auto / span3; } // 첫째줄은 1span 인 첫째와, 3spand인 둘쨰로 가득차고, 그 다음줄에 25% 크기의 3번 4번이 들어왔다가, 5번이 span을 3개 차지하므로 들어가지 못하고 빈공간이 되고, 그 다음줄로 5번째 자식이 3개칸을 차지하게 된다.

만약, grid-auto-flow: dense 옵션을 설정했을 경우,
위와 같은 상황에서 3번 4번이 들어오고 비어버리게 되는 칸을 "크기가 되어 들어갈 수 있는 다음 요소" 로 자동으로 메꾸게 된다.

즉,

1째줄 : 1span 첫째 3span 둘째
2째줄 : 1span 3째 1span 4째 1span 6째, 1span 7째
3째줄 : 3span 5째, 1span 8째
4째줄 : 자식이 없으므로 빈공간 영역 차지 (rows가 5개 갯수로 설정되어있기 떄문)
5째줄 : 자식이 없으므로 빈공간 영역 차지
```

- flex box는 가로나 세로를 한 축으로 정렬하는 1차원 레이아웃이다.

## 🕹 CSS in JS패턴의 장점과 단점
  <table border="1">
	<th>장점</th>
	<tr>
	    <td>클래스명이 컴포넌트별로 유니크한 값으로 설정되기 때문에 css 중복걱정을 하지 않아도 된다</td>
	</tr>
	<tr>
	    <td>css가 컴포넌트 단위로 분리되기 때문에 모듈화하기 쉬우므로 유지보수에 용이하다</td>
	</tr>
<tr>
	    <td>컴포넌트 단위로 분리하여 모듈화하기 쉬우므로, css파일이 늘어남으로 인한 복잡도가 사라진다</td>
	</tr>
<tr>
	    <td>css가 컴포넌트 단위로 스코프가 한정되어 있으므로, 선언의 우선순위에 대한 오류를 신경쓰지 않아도 된다.</td>
	</tr>
         <th>단점</th>
<tr>
	    <td>Js 파일 자체가 크기가 커지게 되므로 로딩 속도가 pure css보다 느리다 ( 만 엄청나게 큰 차이는 아니다)</td>
	</tr>
    </table>

## 🕹 position과 z-index
두 속성 모두 composite layer을 생성하여 gpu 옵션을 이용하여 레이아웃 단위로 스타일링이 적용된다.
<img width="727" alt="스크린샷 2022-03-07 오전 10 08 22" src="https://user-images.githubusercontent.com/58500558/156951316-cbae95a3-2f03-460a-9dc0-0291b047548e.png">

일반적으로 gpu를 사용하는 css가 없을 경우, 브라우저는 서버와 3handshake를 이용해 TCP 연결을 하고, ip주소를 향해 해당 요청을 전달하여 서버로부터 html 문서를 받고, 분석하면서 css, js를 받고 연결을 종료한다
html로는 dom을, css로는 cssom을, js로는 syntax tree를 만든 후 이 결합물을 뷰포트에 플로우와 페인트과정을 거쳐서 만들어내는데

이때 cssom을 만드는 과정에서 만약 해당 스타일링이 gpu를 사용해야 하는 옵션이라면 (ex transfrom, position:abolute등)
즉, 레이아웃 자체를 바꾸는 것이 아니라 새로운 레이어를 만들어내는 옵션이라면 composite layer을 생성하는 과정이 추가된다.

z-index는 마치 포토샵의 레이어 개념과 동일한데, 이 옵션의 크기에 따라 해당 composite layer의 상하관계가 결정된다.
즉, 배치도에 있어 어떤게 더 위에 올라와야 하는지를 정의한다.
